/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.DoctorHistory;

/**
 *
 * @author Sonur
 */
public class Doctor extends javax.swing.JPanel {

    /**
     * Creates new form Doctor
     */
    DoctorHistory dch;
    
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Doctorname = new javax.swing.JLabel();
        DoctorName = new javax.swing.JTextField();
        DoctorID = new javax.swing.JLabel();
        DoctorIDSave = new javax.swing.JTextField();
        SaveDoctordetails = new javax.swing.JButton();

        Doctorname.setText("Doctorname");

        DoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameActionPerformed(evt);
            }
        });

        DoctorID.setText("DoctorID");

        DoctorIDSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorIDSaveActionPerformed(evt);
            }
        });

        SaveDoctordetails.setText("SAVE");
        SaveDoctordetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDoctordetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoctorID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Doctorname, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveDoctordetails)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DoctorName)
                        .addComponent(DoctorIDSave, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctorname)
                    .addComponent(DoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorID)
                    .addComponent(DoctorIDSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(SaveDoctordetails)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorIDSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorIDSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorIDSaveActionPerformed

    private void SaveDoctordetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDoctordetailsActionPerformed
        // TODO add your handling code here:
        String doctorname=Doctorname.getText();
        int id=Integer.parseInt(DoctorID.getText());
   dch.addDoctor();
   
 
      
        
        
        
        
        
        
        
        
        
 
    }//GEN-LAST:event_SaveDoctordetailsActionPerformed

    private void DoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorID;
    private javax.swing.JTextField DoctorIDSave;
    private javax.swing.JTextField DoctorName;
    private javax.swing.JLabel Doctorname;
    private javax.swing.JButton SaveDoctordetails;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
