/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.EmployeeHistory;
import model.Person;

/**
 *
 * @author Sonureddy
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    EmployeeHistory employeeHistory;
    Person person;
    public CreateJPanel(EmployeeHistory employeeHistory) {
        initComponents();
        this.person=person;
        this.employeeHistory=employeeHistory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        numemployeeid = new javax.swing.JTextField();
        numage = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        startdate = new javax.swing.JTextField();
        leveltxt = new javax.swing.JTextField();
        txtteaminfo = new javax.swing.JTextField();
        txtpositiontitle = new javax.swing.JTextField();
        numcontact = new javax.swing.JTextField();
        txtmailaddress = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        uploadfile = new javax.swing.JButton();
        imagelebel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("Employee ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setText("Age:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setText("Level:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setText("Team Info:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setText("Position title:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setText("Start date:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setText("Cell Phone number");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Contact info");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel12.setText("Email address:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        numemployeeid.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        numemployeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numemployeeidActionPerformed(evt);
            }
        });

        numage.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        numage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numageMouseClicked(evt);
            }
        });
        numage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numageActionPerformed(evt);
            }
        });

        txtgender.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtgender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtgenderMouseClicked(evt);
            }
        });
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        startdate.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        startdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startdateActionPerformed(evt);
            }
        });

        leveltxt.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        leveltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leveltxtActionPerformed(evt);
            }
        });

        txtteaminfo.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtteaminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteaminfoActionPerformed(evt);
            }
        });

        txtpositiontitle.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtpositiontitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositiontitleActionPerformed(evt);
            }
        });

        numcontact.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        numcontact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numcontactMouseClicked(evt);
            }
        });
        numcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcontactActionPerformed(evt);
            }
        });

        txtmailaddress.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtmailaddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmailaddressMouseClicked(evt);
            }
        });
        txtmailaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailaddressActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        uploadfile.setText("Upload image");
        uploadfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numage))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numemployeeid))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagelebel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtpositiontitle))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtteaminfo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leveltxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(startdate))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmailaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addComponent(uploadfile)
                .addGap(324, 324, 324))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(imagelebel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(numemployeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(numage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(leveltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtpositiontitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtmailaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadfile))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtpositiontitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositiontitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositiontitleActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
     
        //validation of name
        
        
        
        int age=Integer.parseInt(numage.getText());
        double  mobilenumber=Double.parseDouble(numcontact.getText());
        String email=txtmailaddress.getText();
        int employid=Integer.parseInt(numemployeeid.getText());
        String gender=txtgender.getText();
        int level=Integer.parseInt(leveltxt.getText());
        String name=txtName.getText();
        String posittiontitle=txtpositiontitle.getText();
        String startdate1=startdate.getText();
        String teaminfo=txtteaminfo.getText();
        ImageIcon img=(ImageIcon) imagelebel.getIcon();
        //String impth=jLabel13.getText();
        
       
        
        
      if(txtmailaddress.getText().isEmpty()||txtgender.getText().isEmpty()||
            txtName.getText().isEmpty()|| txtpositiontitle.getText().isEmpty()||startdate.getText().isEmpty()||txtteaminfo.getText().isEmpty()
              ){
            numage.setText(" ");
          numcontact.setText("");
          txtmailaddress.setText("");
          numemployeeid.setText("");
          txtgender.setText("");
          leveltxt.setText("");
          txtName.setText("");
          txtpositiontitle.setText("");
          txtteaminfo.setText("");
          startdate.setText("");
          
        
           JOptionPane.showMessageDialog(this, "No employee is registered ");
          
      }else{
      
        
            Person ppl=employeeHistory.addnewemployee();
        
        ppl.setAge(age);
        ppl.setCellphonenumber(mobilenumber);
        ppl.setEmailaddress(email);
        ppl.setEmployeeid(employid);
        ppl.setGender(gender);
        ppl.setLevel(level);
        ppl.setName(name);
        ppl.setPositiontitle(posittiontitle);
        ppl.setStartdate(name);
        ppl.setTeaminfo(teaminfo);
        ppl.setImage(img);
        
           JOptionPane.showMessageDialog(this, "Employee Information Saved");
           numage.setText(" ");
        numcontact.setText("");
        txtmailaddress.setText("");
        numemployeeid.setText("");
        txtgender.setText("");
        leveltxt.setText("");
        txtName.setText("");
        txtpositiontitle.setText("");
        txtteaminfo.setText("");
        startdate.setText("");
      }
      
        /*
        
        
        
*/
        
        
        /*Person ppl=employeeHistory.addnewemployee();
        
        ppl.setAge(age);
        ppl.setCellphonenumber(mobilenumber);
        ppl.setEmailaddress(email);
        ppl.setEmployeeid(employid);
        ppl.setGender(gender);
        ppl.setLevel(level);
        ppl.setName(name);
        ppl.setPositiontitle(posittiontitle);
        ppl.setStartdate(name);
        ppl.setTeaminfo(teaminfo);
        ppl.setImage(img);
        
            
        
        
        
        
        JOptionPane.showMessageDialog(this, "Employee Information Saved");*/
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
               
        if (txtName.getText().isEmpty()) {
    JOptionPane.showMessageDialog(txtName, "Beware: you left the text field blank");
}
        /*JTextField myField = new JTextField("Default Text"); 
              
                myField.addFocusListener(new FocusListener() {
    public void focusGained(FocusEvent e) {
        myField.setText("");
    }

    public void focusLost(FocusEvent e) {
        // nothing
    }

});
*/
                
// TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtmailaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailaddressActionPerformed

    private void numageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numageActionPerformed
        JOptionPane.showMessageDialog(this, "Age should be less than 60");
// TODO add your handling code here:
    }//GEN-LAST:event_numageActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void numcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numcontactActionPerformed

    private void numemployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numemployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numemployeeidActionPerformed

    private void leveltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leveltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leveltxtActionPerformed

    private void startdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startdateActionPerformed

    private void txtteaminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteaminfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteaminfoActionPerformed

    private void uploadfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadfileActionPerformed
       
       JFileChooser uploadimagefile=new JFileChooser();
       FileNameExtensionFilter ef=new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
       uploadimagefile.addChoosableFileFilter(ef);
       int opendialogue=uploadimagefile.showOpenDialog(null);
       
       if(opendialogue == JFileChooser.APPROVE_OPTION ){
           File selectedpic=uploadimagefile.getSelectedFile();
           String filepath=selectedpic.getAbsolutePath();
                  
        
           
           //JOptionPane.showMessageDialog(null, filepath ");
       
           ImageIcon imgi=new ImageIcon(filepath);
           Image image=imgi.getImage().getScaledInstance(imagelebel.getWidth(),imagelebel.getHeight(),Image.SCALE_SMOOTH );
           imgi=new ImageIcon(image);
           imagelebel.setIcon(imgi);}
        

// TODO add your handling code here:
    }//GEN-LAST:event_uploadfileActionPerformed

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        
JTextField myField = new JTextField("Default Text"); 
              
                
        myField.setText("Enter Valid Name");
    }//GEN-LAST:event_txtNameFocusGained

    private void numageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numageMouseClicked
   
       //OptionPane.showMessageDialog(this, "Age should be less than 60");

        // TODO add your handling code here:
    }//GEN-LAST:event_numageMouseClicked

    private void txtmailaddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmailaddressMouseClicked
        
//ptionPane.showMessageDialog(this, "email should be in format abc@gmail.com");// TODO add your handling code here:
    }//GEN-LAST:event_txtmailaddressMouseClicked

    private void numcontactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numcontactMouseClicked
      //if(numcontact.getText().isEmpty()){
        //  JOptionPane.showMessageDialog(this, "contact number cannot be empty");// TODO add your handling code here:
 
      //}        
// TODO add your handling code here:
    }//GEN-LAST:event_numcontactMouseClicked

    private void txtgenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtgenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagelebel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField leveltxt;
    private javax.swing.JTextField numage;
    private javax.swing.JTextField numcontact;
    private javax.swing.JTextField numemployeeid;
    private javax.swing.JButton save;
    private javax.swing.JTextField startdate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtmailaddress;
    private javax.swing.JTextField txtpositiontitle;
    private javax.swing.JTextField txtteaminfo;
    private javax.swing.JButton uploadfile;
    // End of variables declaration//GEN-END:variables
}
