/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.EmployeeHistory;
import model.Person;

/**
 *
 * @author Sonur
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    EmployeeHistory history;
    Person person;
    public ViewJPanel(EmployeeHistory history) {
        initComponents();
        
        this.history=history;
        this.person=person;
        Person person=new Person();
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        ViewButton = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numemployeeid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numage = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Searchfeild = new javax.swing.JTextField();
        txtgender = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtlabel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtteaminfo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpositiontitel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcellphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imagedsply = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Details");

        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jLabel3.setText("Name:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Employee ID:");

        numemployeeid.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        numemployeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numemployeeidActionPerformed(evt);
            }
        });

        jLabel5.setText("Age:");

        numage.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        numage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numageActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Searchfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchfeildActionPerformed(evt);
            }
        });
        Searchfeild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchfeildKeyReleased(evt);
            }
        });

        txtgender.setText("Gender");

        jLabel2.setText("Start date");

        jLabel6.setText("Level");

        jLabel7.setText("Team Info");

        jLabel8.setText("Poisition title");

        jLabel9.setText("Cell Phone");

        jLabel10.setText("Email Adrress");

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position title", "Cell Phone number", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusTraversalPolicyProvider(true);
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTable1ComponentRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 151, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Delete)
                                    .addComponent(Search))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Searchfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ViewButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(Update))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6)
                                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(numage)
                                            .addComponent(numemployeeid)
                                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(jLabel7)))
                                                .addGap(26, 26, 26))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(txtcellphone)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtpositiontitel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtteaminfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(imagedsply))))
                                    .addComponent(txtlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {gender, numage, numemployeeid, txtName, txtcellphone, txtemail, txtlabel, txtpositiontitel, txtstartdate, txtteaminfo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(Searchfeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(ViewButton)
                    .addComponent(Update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpositiontitel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcellphone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(numemployeeid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numage)
                            .addComponent(jLabel5)))
                    .addComponent(imagedsply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {gender, numage, numemployeeid, txtName, txtcellphone, txtemail, txtlabel, txtpositiontitel, txtstartdate, txtteaminfo});

    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void numemployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numemployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numemployeeidActionPerformed

    private void numageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numageActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       //Delet action 
       
       int selectedrow=jTable1.getSelectedRow();
       if(selectedrow <0){
           
           JOptionPane.showMessageDialog(this, "Please select row to delete");
           return;
        
       }
       
        DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
      
    Person selectedemployee=(Person)tablemodel.getValueAt( selectedrow, 0);

   history.deleteemployee(selectedemployee);   
          JOptionPane.showMessageDialog(this, "Employee Information is deleted");
        populateTable();
  
  
// TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void SearchfeildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchfeildKeyReleased
       
         DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
         String search=Searchfeild.getText();
         TableRowSorter<DefaultTableModel> trs=new  TableRowSorter<DefaultTableModel>(tablemodel);
         jTable1.setRowSorter(trs);
         trs.setRowFilter(RowFilter.regexFilter(search));
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchfeildKeyReleased

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        
       
        
         
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchfeildActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
         
          int selectedrow=jTable1.getSelectedRow();
       if(selectedrow <0){
           
           JOptionPane.showMessageDialog(this, "Please select row to View");
           return;
        
       }
       
        DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
      
    Person selectedemployee=(Person)tablemodel.getValueAt( selectedrow, 0);
    
    txtName.setText(selectedemployee.getName());
    txtcellphone.setText(String.valueOf(selectedemployee.getCellphonenumber()));
    txtemail.setText(selectedemployee.getEmailaddress());
    txtgender.setText(selectedemployee.getGender());
    txtlabel.setText(String.valueOf(selectedemployee.getLevel()));
    txtpositiontitel.setText(selectedemployee.getPositiontitle());
    txtteaminfo.setText(selectedemployee.getTeaminfo());
    numemployeeid.setText(String.valueOf(selectedemployee.getEmployeeid()));
    numage.setText(String.valueOf(selectedemployee.getAge()));
    imagedsply.setIcon(selectedemployee.getImage());
    
    
    
// TODO add your handling code here:
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
          
        DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
      
          int selectedrow=jTable1.getSelectedRow();
       if(selectedrow <0){
           
           JOptionPane.showMessageDialog(this, "Please select row to update");
           return;
        
       }
       Person selectedemployee=(Person)tablemodel.getValueAt( selectedrow, 0);
    
        String name=txtName.getText();
        String email=txtemail.getText();
        String gender=txtgender.getText();
        String posttitle=txtpositiontitel.getText();
        String teaminfo=txtteaminfo.getText();
        double mobilenum=Double.parseDouble(txtcellphone.getText());
        int level=Integer.parseInt(txtlabel.getText());
        int id=Integer.parseInt(numemployeeid.getText());
        int age=Integer.parseInt(numage.getText());
        String startdate=txtstartdate.getText();
        Icon image= imagedsply.getIcon();
        
        history.deleteemployee(selectedemployee);
        Person psn=new Person();
        psn.setName(name);
        psn.setEmailaddress(email);
        psn.setGender(gender);
        psn.setLevel(level);
        psn.setTeaminfo(teaminfo);
        psn.setCellphonenumber(mobilenum);
        psn.setStartdate(startdate);
        psn.setAge(age);
        psn.setImage(image);
    
       jTable1.setValueAt(name,jTable1.getSelectedRow(), 0);
       jTable1.setValueAt(id,jTable1.getSelectedRow(), 1);
       jTable1.setValueAt(age,jTable1.getSelectedRow(), 2);
       jTable1.setValueAt(gender,jTable1.getSelectedRow(), 3);
       jTable1.setValueAt(startdate,jTable1.getSelectedRow(), 4);
       jTable1.setValueAt(level,jTable1.getSelectedRow(), 5);
       jTable1.setValueAt(teaminfo,jTable1.getSelectedRow(), 6);
       jTable1.setValueAt(posttitle,jTable1.getSelectedRow(), 7);
       jTable1.setValueAt(mobilenum,jTable1.getSelectedRow(), 8);
       jTable1.setValueAt(email,jTable1.getSelectedRow(), 9);
       
        
        
       
       history.addupdatedemployee(psn);
       
       JOptionPane.showMessageDialog(this, "Row successfully updated");
       
         
         
        
       
    
         
    

// TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void jTable1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Searchfeild;
    private javax.swing.JButton Update;
    private javax.swing.JButton ViewButton;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel imagedsply;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numage;
    private javax.swing.JTextField numemployeeid;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtcellphone;
    private javax.swing.JTextField txtemail;
    private javax.swing.JLabel txtgender;
    private javax.swing.JTextField txtlabel;
    private javax.swing.JTextField txtpositiontitel;
    private javax.swing.JTextField txtstartdate;
    private javax.swing.JTextField txtteaminfo;
    // End of variables declaration//GEN-END:variables
 
    private void populateTable() {
        
        DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
        tablemodel.setRowCount(0);
        
        for(Person ps : history.getHistory()){
            Object[] row=new Object[10];
            row[3]=ps.getGender();
            row[1]=ps.getEmployeeid();
            row[9]=ps.getEmailaddress();
            row[2]=ps.getAge();
            row[4]=ps.getStartdate();
            row[6]=ps.getTeaminfo();
            row[5]=ps.getLevel();
            row[0]=ps;
            row[8]=ps.getCellphonenumber();
            row[7]=ps.getPositiontitle();
           
            tablemodel.addRow(row);
            
        }
        
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
}
